### ISSUE TITLE
Add Authentication for Bot Usage

### ISSUE THREAD

**Issue by relizerel161** [nessshon/support-bot#14]
Hi!

Could you help us add authentication to our bot? We need to ensure that users can only use the bot after subscribing to a specific chat or channel.

Wishes:
1. The user must subscribe to the specified chat or channel.
2. After subscribing, the user gains access to the bot's functionality.
3. If the user is not subscribed, the bot should notify them about the need to subscribe.

I haven't fully figured out your bot yet, but if you tell me what I need to do, I might be able to do it myself.

**Comment by nessshon** [comment]
@relizerel161, Hi! You can seek help and request bot upgrades on freelance platforms.
