### ISSUE TITLE
bot startup error

### ISSUE THREAD

**Issue by wmzaru** [nessshon/support-bot#15]
When running the bot with the command **`docker-compose up --build`** the following error appears. server “**aeza**”
![feedback](https://github.com/user-attachments/assets/5aaab575-94b2-4c88-9e7e-cde34cccf8fd)

**Comment by nessshon** [comment]
@wmzaru 

```
sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
```
