### ISSUE TITLE
Don't create topic on start and do only after first message.

### ISSUE THREAD

**Issue by ShadowsSide** [nessshon/support-bot#6]
Hi,there

I found that the bot will generate a topic after clicking /start, instead of sending the first message.

Many people are just curious rather than really want to chat with you.

It's more logical and doesn't make as much noise.

Thank you for your hard work~

**Comment by nessshon** [comment]
@ShadowsSide, Hi! Thanks for your feedback!
This is done to improve the efficiency of the bot and track the activity and launches of the bot.

You can disable this by removing the [line](https://github.com/nessshon/support-bot/blob/main/app/bot/handlers/private/command.py#L42) of code.
